language: ruby
script: rake ci
rvm:
  - 2.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-head
gemfile:
  - Gemfile
  - Gemfile-jruby
matrix:
  exclude:
    - rvm: 2.0
      gemfile: Gemfile-jruby
    - rvm: 2.1
      gemfile: Gemfile-jruby
    - rvm: ruby-head
      gemfile: Gemfile-jruby
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: Gemfile
    - rvm: rbx-2
      gemfile: Gemfile-jruby
    - rvm: rbx-head
      gemfile: Gemfile-jruby
  allow_failures:
    - rvm: rbx-2
    - rvm: rbx-head
