sudo: required
dist: trusty

language: ruby
before_install:
# This was an attempt to get rbx working under trusty. Seems there's some sort of conflict with libssl going on.
#- sudo apt-get update && sudo apt-get install openssl libssl1.0.0 --yes
#- sudo apt-get --purge remove libssl1.0.0 --yes
#- sudo apt-get install libssl1.0.0 --yes
- gem install bundler
install: bundle install --jobs 3 --retry 3 --without mutant --path vendor/bundle
script: bundle exec rake ci
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
    - rvm: jruby-head
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: rbx
addons:
  code_climate:
    repo_token: 5ac0735331c1749a461eae94f89cd2011cc001979f9941d7241f97caeff7bde1

cache:
  directories:
  - vendor
