language: ruby
script: rake ci
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - ruby-head
  - rbx-2.1
  - rbx-2.2
  - rbx-2.3
matrix:
  include:
    - rvm: jruby
      gemfile: Gemfile-ruby
    - rvm: jruby
      gemfile: Gemfile-ruby
      env: JRUBY_OPTS='--2.0'
    - rvm: jruby-head
      gemfile: Gemfile-ruby
    - rvm: jruby-head
      gemfile: Gemfile-ruby
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2.1
    - rvm: rbx-2.2
    - rvm: rbx-2.3
