language: ruby
script: rake ci
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  #- mruby-head
  #- rbx-2.1
  #- rbx-2.2
  #- rbx-2.3
  - rbx-2.4
  - jruby
  - jruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
    - rvm: jruby-head
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: 1.9.3
    - rvm: jruby
    - rvm: jruby-head
    - rvm: mruby-head
    - rvm: rbx-2.1
    - rvm: rbx-2.2
    - rvm: rbx-2.3
    - rvm: rbx-2.4
addons:
  code_climate:
    repo_token: 5ac0735331c1749a461eae94f89cd2011cc001979f9941d7241f97caeff7bde1
