language: ruby
before_install: gem update bundler
install: bundle install --jobs 3 --retry 3 --without mutant
script: rake ci
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2.4
  - rbx-2.5
  - rbx-2.6
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
    - rvm: jruby-head
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: mruby-head
    - rvm: rbx-2.4
    - rvm: rbx-2.5
    - rvm: rbx-2.6
addons:
  code_climate:
    repo_token: 5ac0735331c1749a461eae94f89cd2011cc001979f9941d7241f97caeff7bde1
